### ISSUE TITLE
Questions about dataset acquisition

### ISSUE THREAD

**Issue by pzSuen** [agentdr1/LA_MIL#1]
Hello.
Your work is imposing, and the experiments are very complete.

I've been working on something similar recently, but the data is still quite limited. I want to utilize the TCGA dataset, but struggling to know how to get the labels. Your work has been like a light to guide me.

You say in the article that you obtained the images at TCGA, the manual annotation at kather.ai, the genetic information at xenabrowser.net, and the microsatellite stability/instability (MSS/MSI) and TMB information at cbioportal.org.
I am not a native English speaker and lack of medical background. So I need some clarification about how to use the above websites. 
Can you describe in more detail how you obtained the above data?

Thank you very much for your help. 
I am looking forward to hearing from you.

Yours,
pzSuen

**Comment by agentdr1** [comment]
Hi, 
thanks for reaching out and your kind words. You might want to check out [Kather's metadata repo](https://github.com/KatherLab/cancer-metadata).

**TMB and MSI**: https://www.cbioportal.org/datasets
Often there are several studies for your particular cancer type / data set available, we used the PanCancer Atlas study, e.g. for TCGA COAD/READ you might check out [this page]( https://www.cbioportal.org/study/summary?id=coadread_tcga_pan_can_atlas_2018), then navigate to the top right and click on charts (clinical) and scroll down until you find TMB (nonsynonymous) and hit the box. Next, if you scroll down the boxes including statistics plots, find e.g. MSI or TMB and move cursor into the box, in the right upper corner you can find three lines and a download button. 
**Manual tumor annotations from Kather:** check out [this page](https://zenodo.org/record/5320076#.Y24iV-zMLdo)

You can match annotations using the patient id (TCGA-XX-XXXX), also contained in the TCGA slide names.

**Comment by pzSuen** [comment]
Thank you very much for your timely and generous answers. I will need some time to digest this information.

If I have any new questions, I will ask you again.
